addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - CHEF_VERSION=15 INSTANCE=cron-ubuntu-1604
  - CHEF_VERSION=15 INSTANCE=cron-ubuntu-1804
  - CHEF_VERSION=15 INSTANCE=cron-centos-6
  - CHEF_VERSION=15 INSTANCE=cron-centos-7
  - CHEF_VERSION=15 INSTANCE=cron-opensuse-leap-42
  - CHEF_VERSION=15 INSTANCE=delete-validation-ubuntu-1804
  - CHEF_VERSION=15 INSTANCE=service-systemd-amazonlinux-2
  - CHEF_VERSION=15 INSTANCE=service-systemd-centos-7
  - CHEF_VERSION=15 INSTANCE=service-systemd-debian-9
  - CHEF_VERSION=15 INSTANCE=service-systemd-debian-10
  - CHEF_VERSION=15 INSTANCE=service-systemd-fedora-latest
  - CHEF_VERSION=15 INSTANCE=service-systemd-opensuse-leap-42
  - CHEF_VERSION=15 INSTANCE=service-systemd-ubuntu-1604
  - CHEF_VERSION=15 INSTANCE=service-systemd-ubuntu-1804
  - CHEF_VERSION=15 INSTANCE=timer-systemd-amazonlinux-2
  - CHEF_VERSION=15 INSTANCE=timer-systemd-centos-7
  - CHEF_VERSION=15 INSTANCE=timer-systemd-debian-9
  - CHEF_VERSION=15 INSTANCE=timer-systemd-debian-10
  - CHEF_VERSION=15 INSTANCE=timer-systemd-fedora-latest
  - CHEF_VERSION=15 INSTANCE=timer-systemd-opensuse-leap-42
  - CHEF_VERSION=15 INSTANCE=timer-systemd-ubuntu-1604
  - CHEF_VERSION=15 INSTANCE=timer-systemd-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=cron-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=cron-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=cron-centos-6
  - CHEF_VERSION=14 INSTANCE=cron-centos-7
  - CHEF_VERSION=14 INSTANCE=cron-opensuse-leap-42
  - CHEF_VERSION=14 INSTANCE=delete-validation-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=service-systemd-amazonlinux-2
  - CHEF_VERSION=14 INSTANCE=service-systemd-centos-7
  - CHEF_VERSION=14 INSTANCE=service-systemd-debian-9
  - CHEF_VERSION=14 INSTANCE=service-systemd-debian-10
  - CHEF_VERSION=14 INSTANCE=service-systemd-fedora-latest
  - CHEF_VERSION=14 INSTANCE=service-systemd-opensuse-leap-42
  - CHEF_VERSION=14 INSTANCE=service-systemd-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=service-systemd-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=timer-systemd-amazonlinux-2
  - CHEF_VERSION=14 INSTANCE=timer-systemd-centos-7
  - CHEF_VERSION=14 INSTANCE=timer-systemd-debian-9
  - CHEF_VERSION=14 INSTANCE=timer-systemd-debian-10
  - CHEF_VERSION=14 INSTANCE=timer-systemd-fedora-latest
  - CHEF_VERSION=14 INSTANCE=timer-systemd-opensuse-leap-42
  - CHEF_VERSION=14 INSTANCE=timer-systemd-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=timer-systemd-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=cron-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=cron-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=cron-centos-6
  - CHEF_VERSION=13 INSTANCE=cron-centos-7
  - CHEF_VERSION=13 INSTANCE=cron-opensuse-leap-42
  - CHEF_VERSION=13 INSTANCE=delete-validation-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=service-systemd-amazonlinux-2
  - CHEF_VERSION=13 INSTANCE=service-systemd-centos-7
  - CHEF_VERSION=13 INSTANCE=service-systemd-debian-9
  - CHEF_VERSION=13 INSTANCE=service-systemd-debian-10
  - CHEF_VERSION=13 INSTANCE=service-systemd-fedora-latest
  - CHEF_VERSION=13 INSTANCE=service-systemd-opensuse-leap-42
  - CHEF_VERSION=13 INSTANCE=service-systemd-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=service-systemd-ubuntu-1804
  - CHEF_VERSION=13 INSTANCE=timer-systemd-amazonlinux-2
  - CHEF_VERSION=13 INSTANCE=timer-systemd-centos-7
  - CHEF_VERSION=13 INSTANCE=timer-systemd-debian-9
  - CHEF_VERSION=13 INSTANCE=timer-systemd-debian-10
  - CHEF_VERSION=13 INSTANCE=timer-systemd-fedora-latest
  - CHEF_VERSION=13 INSTANCE=timer-systemd-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=timer-systemd-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
