sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - CHEF_VERSION=14 INSTANCE=cron-ubuntu-1404
  - CHEF_VERSION=14 INSTANCE=cron-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=cron-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=cron-centos-6
  - CHEF_VERSION=14 INSTANCE=cron-centos-7
  - CHEF_VERSION=14 INSTANCE=delete-validation-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=delete-validation-centos-7
  - CHEF_VERSION=14 INSTANCE=service-upstart-ubuntu-1404
  - CHEF_VERSION=14 INSTANCE=service-systemd-centos-7
  - CHEF_VERSION=14 INSTANCE=service-systemd-debian-8
  - CHEF_VERSION=14 INSTANCE=service-systemd-debian-9
  - CHEF_VERSION=14 INSTANCE=service-systemd-fedora-latest
  - CHEF_VERSION=14 INSTANCE=service-systemd-opensuse-leap
  - CHEF_VERSION=14 INSTANCE=service-systemd-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=service-init-centos-6
  - CHEF_VERSION=14 INSTANCE=service-init-amazonlinux
  - CHEF_VERSION=13 INSTANCE=cron-ubuntu-1404
  - CHEF_VERSION=13 INSTANCE=cron-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=cron-centos-6
  - CHEF_VERSION=13 INSTANCE=cron-centos-7
  - CHEF_VERSION=13 INSTANCE=delete-validation-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=delete-validation-centos-7
  - CHEF_VERSION=13 INSTANCE=service-upstart-ubuntu-1404
  - CHEF_VERSION=13 INSTANCE=service-systemd-amazonlinux-2
  - CHEF_VERSION=13 INSTANCE=service-systemd-centos-7
  - CHEF_VERSION=13 INSTANCE=service-systemd-debian-8
  - CHEF_VERSION=13 INSTANCE=service-systemd-debian-9
  - CHEF_VERSION=13 INSTANCE=service-systemd-fedora-latest
  - CHEF_VERSION=13 INSTANCE=service-systemd-opensuse-leap
  - CHEF_VERSION=13 INSTANCE=service-systemd-ubuntu-1604
  - CHEF_VERSION=13 INSTANCE=service-init-centos-6
  - CHEF_VERSION=13 INSTANCE=service-init-amazonlinux

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
